
export const base = {
  name: '基础的',
  list: [
    {
      info: {
        name: 'textbox',
        img: new URL(
          './36a30e9e_112f_4f86_908f_36e473b6717d_font_c8f149ad38.png',
          import.meta.url
        ).href,
      },
      json: {
        id: '4b675559-54c2-48d0-a6bc-b0b4cb61fcc3',
        top: 80.3504,
        fill: '#000000FF',
        left: 49.5,
        path: null,
        text: '标题文字',
        type: 'textbox',
        angle: 0,
        flipX: false,
        flipY: false,
        skewX: 0,
        skewY: 0,
        width: 400,
        height: 90.4,
        scaleX: 1,
        scaleY: 1,
        shadow: '',
        stroke: null,
        styles: [],
        opacity: 1,
        originX: 'left',
        originY: 'top',
        version: '5.4.0',
        visible: true,
        fillRule: 'nonzero',
        fontSize: 80,
        minWidth: 20,
        overline: false,
        pathSide: 'left',
        direction: 'ltr',
        fontStyle: 'normal',
        pathAlign: 'baseline',
        textAlign: 'left',
        underline: false,
        fontFamily: 'arial',
        fontWeight: 'normal',
        lineHeight: 1.16,
        paintFirst: 'stroke',
        selectable: true,
        charSpacing: 0,
        hasControls: true,
        linethrough: false,
        strokeWidth: 1,
        strokeLineCap: 'butt',
        strokeUniform: false,
        strokeLineJoin: 'miter',
        backgroundColor: '',
        pathStartOffset: 0,
        splitByGrapheme: true,
        strokeDashArray: null,
        strokeDashOffset: 0,
        strokeMiterLimit: 4,
        textBackgroundColor: '',
        globalCompositeOperation: 'source-over',
      },
    },
    {
      info: {
        name: 'image',
        img: new URL(
          './frame_0_delay-0.45s.gif',
          import.meta.url
        ).href,
      },
      json: {
        "name":"图片",
        "type": "image",
        "version": "5.4.2",
        "originX": "left",
        "originY": "top",
        "left": 0,
        "top": 0,
        "width": 800,
        "height": 800,
        "fill": "rgb(0,0,0)",
        "stroke": null,
        "strokeWidth": 0,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeDashOffset": 0,
        "strokeLineJoin": "miter",
        "strokeUniform": false,
        "strokeMiterLimit": 4,
        "scaleX": 1,
        "scaleY": 1,
        "angle": 0,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "skewX": 0,
        "skewY": 0,
        "cropX": 0,
        "cropY": 0,
        "id": "a07091ca-8be9-4a26-850f-eb1441c4d778",
        "selectable": true,
        "hasControls": true,
        "src":  new URL(
          './frame_0_delay-0.45s.gif',
          import.meta.url
        ).href,
        "crossOrigin": "anonymous",
        "filters": []
      },
    },
    {
      info: {
        name: 'textbox',
        img: new URL(
          './往 下 滑 查 看 更 多 详 情 图.png',
          import.meta.url
        ).href,
      },
      json:{"subTargetCheck":false,"interactive":false,"id":"545a0390-43e7-4291-bb59-f47a074976f8","selectable":true,"type":"Group","version":"6.5.4","originX":"left","originY":"top","left":739,"top":284.2282,"width":61,"height":371,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeUniform":false,"strokeMiterLimit":4,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":0.9,"shadow":null,"visible":true,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","skewX":0,"skewY":0,"layoutManager":{"type":"layoutManager","strategy":"fit-content"},"objects":[{"rx":20,"ry":20,"id":"3a37698d-b435-4846-b060-f65561c1c208","selectable":true,"type":"Rect","version":"6.5.4","originX":"left","originY":"top","left":-30.5,"top":-185.5,"width":60,"height":370,"fill":"#f2f3f3","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeUniform":false,"strokeMiterLimit":4,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":"","visible":true,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","skewX":0,"skewY":0},{"fontSize":60,"fontWeight":"normal","fontFamily":"优设鲨鱼菲特健康体","fontStyle":"normal","lineHeight":1.16,"text":"往\n下\n滑\n查\n看\n更\n多\n详\n情\n图","charSpacing":0,"textAlign":"center","styles":[],"path":null,"pathStartOffset":0,"pathSide":"left","pathAlign":"baseline","underline":false,"overline":false,"linethrough":false,"textBackgroundColor":"","direction":"ltr","minWidth":20,"splitByGrapheme":true,"id":"3a37698d-b435-4846-b060-f65561c1c201","selectable":true,"type":"Textbox","version":"6.5.4","originX":"left","originY":"top","left":-15.6396,"top":-167.2342,"width":72.4299,"height":775.632,"fill":"#000000FF","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeUniform":false,"strokeMiterLimit":4,"scaleX":0.3955,"scaleY":0.3955,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":"","visible":true,"backgroundColor":"","fillRule":"nonzero","paintFirst":"stroke","globalCompositeOperation":"source-over","skewX":0,"skewY":0},{"fontSize":60,"fontWeight":"normal","fontFamily":"arial","fontStyle":"normal","lineHeight":1.16,"text":">>","charSpacing":0,"textAlign":"left","styles":[],"path":null,"pathStartOffset":0,"pathSide":"left","pathAlign":"baseline","underline":false,"overline":false,"linethrough":false,"textBackgroundColor":"","direction":"ltr","minWidth":20,"splitByGrapheme":true,"id":"3a37698d-b435-4846-b060-f65561c1c209","selectable":true,"type":"Textbox","version":"6.5.4","originX":"left","originY":"top","left":21.2572,"top":146.9424,"width":74.8414,"height":67.8,"fill":"#000000FF","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeUniform":false,"strokeMiterLimit":4,"scaleX":0.273,"scaleY":0.6961,"angle":90,"flipX":false,"flipY":false,"opacity":1,"shadow":"","visible":true,"backgroundColor":"","fillRule":"nonzero","paintFirst":"stroke","globalCompositeOperation":"source-over","skewX":0,"skewY":0}]}
    }
  ],
};
