
export const base = {
  name: '基础的',
  list: [
    {
      info: {
        name: 'textbox',
        img: new URL(
          './36a30e9e_112f_4f86_908f_36e473b6717d_font_c8f149ad38.png',
          import.meta.url
        ).href,
      },
      json: {
        id: '4b675559-54c2-48d0-a6bc-b0b4cb61fcc3',
        top: 80.3504,
        fill: '#000000FF',
        left: 49.5,
        path: null,
        text: '标题文字',
        type: 'textbox',
        angle: 0,
        flipX: false,
        flipY: false,
        skewX: 0,
        skewY: 0,
        width: 400,
        height: 90.4,
        scaleX: 1,
        scaleY: 1,
        shadow: '',
        stroke: null,
        styles: [],
        opacity: 1,
        originX: 'left',
        originY: 'top',
        version: '5.4.0',
        visible: true,
        fillRule: 'nonzero',
        fontSize: 80,
        minWidth: 20,
        overline: false,
        pathSide: 'left',
        direction: 'ltr',
        fontStyle: 'normal',
        pathAlign: 'baseline',
        textAlign: 'left',
        underline: false,
        fontFamily: 'arial',
        fontWeight: 'normal',
        lineHeight: 1.16,
        paintFirst: 'stroke',
        selectable: true,
        charSpacing: 0,
        hasControls: true,
        linethrough: false,
        strokeWidth: 1,
        strokeLineCap: 'butt',
        strokeUniform: false,
        strokeLineJoin: 'miter',
        backgroundColor: '',
        pathStartOffset: 0,
        splitByGrapheme: true,
        strokeDashArray: null,
        strokeDashOffset: 0,
        strokeMiterLimit: 4,
        textBackgroundColor: '',
        globalCompositeOperation: 'source-over',
      },
    },
    {
      info: {
        name: 'image',
        img: new URL(
          './frame_0_delay-0.45s.gif',
          import.meta.url
        ).href,
      },
      json: {
        "name":"图片",
        "type": "image",
        "version": "5.4.2",
        "originX": "left",
        "originY": "top",
        "left": 1.2,
        "top": 1.2,
        "width": 800,
        "height": 800,
        "fill": "rgb(0,0,0)",
        "stroke": null,
        "strokeWidth": 0,
        "strokeDashArray": null,
        "strokeLineCap": "butt",
        "strokeDashOffset": 0,
        "strokeLineJoin": "miter",
        "strokeUniform": false,
        "strokeMiterLimit": 4,
        "scaleX": 0.997,
        "scaleY": 0.997,
        "angle": 0,
        "flipX": false,
        "flipY": false,
        "opacity": 1,
        "shadow": null,
        "visible": true,
        "backgroundColor": "",
        "fillRule": "nonzero",
        "paintFirst": "fill",
        "globalCompositeOperation": "source-over",
        "skewX": 0,
        "skewY": 0,
        "cropX": 0,
        "cropY": 0,
        "id": "a07091ca-8be9-4a26-850f-eb1441c4d778",
        "selectable": true,
        "hasControls": true,
        "src":  new URL(
          './frame_0_delay-0.45s.gif',
          import.meta.url
        ).href,
        "crossOrigin": "anonymous",
        "filters": []
      },
    },
  ],
};


